name: Playwright Tests
on: workflow_dispatch

jobs:
  tests: 
    runs-on: ubuntu-latest
    environment: Playwright
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: |
        cd Playwright
        npm install

    - name: Run Playwright tests
      run: |
        cd Playwright
        npx playwright test BD_card_moving.spec.ts

    - name: Upload Playwright report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: Playwright/playwright-report/
        retention-days: 30
