name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build the project
        run: dotnet build

      - name: Publish the project
        run: dotnet publish --configuration Release --output ./publish_output

      - name: Copy files to local folder
        run: |
          cp -r ./publish_output/* /"C:\Users\mohil\ILIYAS\Courses\Devops\Task 1 - 14-10-2024\publish\HelloWorldApi.exe"

      - name: Run the application
        run: |
          # Run the application from the deployed folder
          cd "C:\Users\mohil\ILIYAS\Courses\Devops\Task 1 - 14-10-2024\publish\"
          dotnet HelloWorldApi.dll 
