name: CI Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build project
        run: dotnet build

      - name: Scan with Checkmarx
        run: echo "Running Checkmarx scan..."  # Replace with actual Checkmarx command

      - name: Publish to Octopus
        run: echo "Publishing to Octopus Deploy..."
