name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies and build
      - name: Restore dependencies
        run: dotnet restore

      - name: Build the app
        run: dotnet build --configuration Release

      # Package the app 
      - name: Publish the app
        run: dotnet publish -c Release -o ./"C:\Users\mohil\ILIYAS\Courses\Devops\Task 1 - 14-10-2024\HelloWorldApi\bin\Release\net8.0\publish"

      # Upload the build artifact to Octopus Deploy
      - name: Push Package to Octopus Deploy
        uses: OctopusDeploy/push-package-action@v1
        with:
          package: './output/YourApp.zip'  # Path to the built app package
          server: ${{ secrets.OCTOPUS_SERVER_URL }}
          api_key: ${{ secrets.OCTOPUS_API_KEY }}

      # Create a release in Octopus Deploy
      - name: Create Release in Octopus Deploy
        uses: OctopusDeploy/create-release-action@v1
        with:
          project: "Your Project Name"
          version: "1.0.0"  # Sync with GitHub release versioning
          server: ${{ secrets.OCTOPUS_SERVER_URL }}
          api_key: ${{ secrets.OCTOPUS_API_KEY }}
