name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Pack project
      run: dotnet publish -c Release -o ./artifacts

    - name: Push to Octopus Deploy
      run: |
        curl -X POST "$OCTOPUS_SERVER/api/deployments" \
        -H "X-Octopus-ApiKey: ${{ secrets.OCTOPUS_API_KEY }}" \
        -d @deploy.json
      env:
        OCTOPUS_SERVER: ${{ secrets.OCTOPUS_SERVER }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
