name: Pull Request Approval

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  request-approval:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Send email notification
        env:
          SMTP_SERVER: smtp4dev  # Replace with your SMTP server
          SMTP_PORT: 25  # Change according to your SMTP server settings
          EMAIL: "rabpo@eg.dk"  # Update to the approver's email
          SENDER_EMAIL: "noreply@mohil@eg.dk"  # Replace with sender's email
          EMAIL_SUBJECT: "Approval Request for Pull Request"
          EMAIL_BODY: "A new pull request has been created. Please review it."
        run: |
          python -m pip install secure-smtplib
          echo "Sending email to $EMAIL for PR approval..."
          python - <<EOF
          import smtplib
          from email.mime.text import MIMEText
          from email.mime.multipart import MIMEMultipart
          
          # SMTP server configuration
          smtp_server = "$SMTP_SERVER"
          smtp_port = $SMTP_PORT
          sender_email = "$SENDER_EMAIL"
          receiver_email = "$EMAIL"
          
          # Create the email message
          msg = MIMEMultipart()
          msg['From'] = sender_email
          msg['To'] = receiver_email
          msg['Subject'] = "$EMAIL_SUBJECT"
          
          # Add body to the email
          msg.attach(MIMEText("$EMAIL_BODY", 'plain'))
          
          # Send the email
          try:
              with smtplib.SMTP(smtp_server, smtp_port) as server:
                  server.sendmail(sender_email, receiver_email, msg.as_string())
                  print("Email sent to $EMAIL.")
          except Exception as e:
              print(f"Failed to send email: {e}")
          EOF
